# Generated by Django 5.1.2 on 2024-10-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saac_app', '0003_event_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start',
        ),
    ]
