# Generated by Django 5.1.2 on 2024-10-31 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saac_app', '0004_rename_date_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hello',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 31, 5, 40, 1, 839068, tzinfo=datetime.timezone.utc)),
        ),
    ]
