# Generated by Django 5.1.2 on 2024-10-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saac_app', '0009_rename_name_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subcommittee',
            field=models.CharField(choices=[('BeOregon', 'BeOregon'), ('Athlete Unification', 'Athlete Unification'), ('Duck The Stigma', 'Duck The Stigma'), ('O Heroes', 'OHeroes'), ('Women Of Oregon', 'Women Of Oregon'), ('SAAC', 'SAAC'), ('Ducks Go Pro', 'Ducks Go Pro')], max_length=20),
        ),
    ]
