# Generated by Django 5.1.2 on 2024-12-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saac_app', '0011_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grad_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
