# Generated by Django 5.1.2 on 2024-12-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saac_app', '0012_customuser_grad_year'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
