# Generated by Django 5.1.2 on 2024-12-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saac_app', '0013_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sport',
            field=models.CharField(choices=[('W crobatics & Tumbling', 'W Acrobatics & Tumbling'), ('W Basketball', 'W Basketball'), ('W Beach Volleyball', 'W Beach Volleyball'), ('W Cross Country', 'W Cross Country'), ('W Golf', 'W Golf'), ('W Lacrosse', 'W Lacrosse'), ('W Soccer', 'W Soccer'), ('W Softball', 'W Softball'), ('W Tennis', 'W Tennis'), ('W Track & Field', 'W Track & Field'), ('W Volleyball', 'W Volleyball'), ('M Baseball', 'M Baseball'), ('M Basketball', 'M Basketball'), ('M Cross Country', 'M Cross Country'), ('M Football', 'M Football'), ('M Golf', 'M Golf'), ('M Tennis', 'M Tennis'), ('M Track & Field', 'M Track & Field')], max_length=25),
        ),
    ]
